frontend:
  name: frontend-service
  image: microservices-k8s-helm-istio-frontend-service
  tag: latest
  port: 5000
  nodePort: 30000
  replicas: 1

order:
  name: order-service
  image: microservices-k8s-helm-istio-order-service
  tag: latest
  port: 5001
  replicas: 1

product:
  name: product-service
  image: microservices-k8s-helm-istio-product-service
  tag: latest
  port: 5002
  replicas: 1